#![allow(unused)]

mod find_all_anagrams_in_a_string;
mod find_the_index_of_the_first_occurrence_in_a_string;
mod contains_duplicate_2;
mod minimum_recolors_to_get_k_consecutive_black_blocks;
mod minimum_difference_between_highest_and_lowest_of_k_scores;
mod number_of_sub_arrays_of_size_k_and_average_greater_than_or_equal_to_threshold;
mod grumpy_bookstore_owner;
mod alternating_groups_1;
mod alternating_groups_2;
mod longest_substring_without_repeating_characters;
mod longest_substring_with_at_most_two_distinct_characters;
mod longest_repeating_character_replacement;
mod permutation_in_string;
mod longest_substring_with_at_most_k_distinct_characters;

fn main() {
    longest_substring_with_at_most_k_distinct_characters::main();
}
